### ISSUE TITLE
不再改进一下么?

### ISSUE THREAD

**Issue by at15** [codeworm96/web-starter#1]
比如加点css,用一下兰大姐的bootstrap之类的.

如果认为太简单的话，试一下front里的任务咩?
因为我们主要是用angularjs,jquery基本上都是放到angularjs的directive里用的.

最后一个问题，挖掘机那家强? :)

**Comment by codeworm96** [comment]
不好意思。课余时间不够，所以退出招新。

**Comment by at15** [comment]
oh…好吧.

发自 Windows 邮件

发件人: codeworm96
发送时间: ‎2014‎年‎10‎月‎7‎日, ‎星期二 ‎20‎:‎25
收件人: codeworm96/web-starter
抄送: Pillar Guo

不好意思。课余时间不够，所以退出招新。
